version: '3.8'

services:
  easy-xray:
    env_file:
      - .env.local
    build:
      args:
        SERVER_IP: 127.0.0.1
        WEBSITE_URL: www.example.com
        MODE: dev
      target: dev
    volumes:
      - ./server/src:/server/src
