version: '3.8'

services:
  easy-xray:
    build:
      args:
        SERVER_IP: 127.0.0.1
        WEBSITE_URL: www.example.com
        MODE: dev
      target: dev
    volumes:
      - easy-xray:/easy-xray
      - ./server:/server
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"

volumes:
  easy-xray:
